export default [
    {
        id: 1,
        title: '哆啦A梦01',
        brand: 'brand01',
        color: '白色',
        size: "L号",
        src: '/remote-data/image/01.png',
        price: 400,
        num: 1288,
    },
    {
        id: 2,
        title: '火箭01',
        brand: 'brand02',
        color: '白色',
        size: "M号",
        src: '/remote-data/image/02.png',
        price: 310,
        num: 1188,
    },
    {
        id: 3,
        title: '卡通猫01',
        brand: 'brand03',
        color: ' 黄色',
        size: "XL号",
        src: '/remote-data/image/03.png',
        price: 500,
        num: 2288,
    },
    {
        id: 4,
        title: '状元01',
        brand: 'brand04',
        color: '红色',
        size: "S号",
        src: '/remote-data/image/04.png',
        price: 300,
        num: 1888,
    },
    {
        id: 5,
        title: '哆啦A梦02',
        brand: 'brand01',
        color: '白色',
        size: "XL号",
        src: '/remote-data/image/01.png',
        price: 800,
        num: 1578,
    },
    {
        id: 6,
        title: '火箭02',
        brand: 'brand02',
        color: '金色',
        size: "L号",
        src: '/remote-data/image/02.png',
        price: 1200,
        num: 1488,
    },
    {
        id: 7,
        title: '卡通猫02',
        brand: 'brand03',
        color: '蓝色',
        size: "L号",
        src: '/remote-data/image/03.png',
        price: 2500,
        num: 788,
    },
    {
        id: 8,
        title: '状元02',
        brand: 'brand04',
        color: '金色',
        size: "XL号",
        src: '/remote-data/image/01.png',
        price: 150,
        num: 1898,
    },
    {
        id: 9,
        title: '哆啦A梦03',
        brand: 'brand01',
        color: '蓝色',
        size: "S号",
        src: '/remote-data/image/01.png',
        price: 100,
        num: 2878,
    },
    {
        id: 10,
        title: '卡通猫03',
        brand: 'brand03',
        color: '金色',
        size: "M号",
        src: '/remote-data/image/03.png',
        price: 90,
        num: 2298,
    }
]