export default [
    {
        id: 1,
        title: '哆啦A梦01',
        brand: 'brand01',
        color: '白色',
        size: "L号",
        src: "https://raw.githubusercontent.com/Anani1994/vue-market/master/remote-data/image/01.png",
        price: 400,
        num: 1288,
    },
    {
        id: 2,
        title: '哆啦A梦02',
        brand: 'brand02',
        color: '白色',
        size: "M号",
        src: "https://raw.githubusercontent.com/Anani1994/vue-market/master/remote-data/image/01.png",
        price: 310,
        num: 1188,
    },
    {
        id: 3,
        title: '哆啦A梦03',
        brand: 'brand03',
        color: ' 黄色',
        size: "XL号",
        src: "https://raw.githubusercontent.com/Anani1994/vue-market/master/remote-data/image/01.png",
        price: 500,
        num: 2288,
    },
    {
        id: 4,
        title: '哆啦A梦04',
        brand: 'brand04',
        color: '红色',
        size: "S号",
        src: "https://raw.githubusercontent.com/Anani1994/vue-market/master/remote-data/image/01.png",
        price: 300,
        num: 1888,
    },
    {
        id: 5,
        title: '哆啦A梦05',
        brand: 'brand01',
        color: '白色',
        size: "XL号",
        src: "https://raw.githubusercontent.com/Anani1994/vue-market/master/remote-data/image/01.png",
        price: 800,
        num: 1578,
    },
    {
        id: 6,
        title: '哆啦A梦06',
        brand: 'brand02',
        color: '金色',
        size: "L号",
        src: "https://raw.githubusercontent.com/Anani1994/vue-market/master/remote-data/image/01.png",
        price: 1200,
        num: 1488,
    },
    {
        id: 7,
        title: '哆啦A梦07',
        brand: 'brand03',
        color: '蓝色',
        size: "L号",
        src: "https://raw.githubusercontent.com/Anani1994/vue-market/master/remote-data/image/01.png",
        price: 2500,
        num: 788,
    },
    {
        id: 8,
        title: '哆啦A梦08',
        brand: 'brand04',
        color: '金色',
        size: "XL号",
        src: "https://raw.githubusercontent.com/Anani1994/vue-market/master/remote-data/image/01.png",
        price: 150,
        num: 1898,
    },
    {
        id: 9,
        title: '哆啦A梦09',
        brand: 'brand01',
        color: '蓝色',
        size: "S号",
        src: "https://raw.githubusercontent.com/Anani1994/vue-market/master/remote-data/image/01.png",
        price: 100,
        num: 2878,
    },
    {
        id: 10,
        title: '哆啦A梦10',
        brand: 'brand03',
        color: '金色',
        size: "M号",
        src: "https://raw.githubusercontent.com/Anani1994/vue-market/master/remote-data/image/01.png",
        price: 90,
        num: 2298,
    }
]